# -*- coding: utf-8 -*-
"""HR_attribution_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5pOxIzpVoft6DayQMHd4MPwpnhljJAM
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

df=pd.read_csv("/content/HumanResources.csv")

df

df['Attrition']=df['termination_date'].notna().astype(int)

"""drop un-necessary coumns"""

df.drop(columns=['employee_id','first_name','last_name','termination_date'],inplace=True)

"""date feature engineering

"""

df['hire_date']=pd.to_datetime(df['hire_date'])
df['birth_date']=pd.to_datetime(df['birth_date'])

df['age']=(pd.Timestamp.today() - df['birth_date']).dt.days //365
df['experience_years']=(pd.Timestamp.today() - df['hire_date']).dt.days //365

df.drop(columns=['hire_date','birth_date'],inplace=True)

"""Encode binary and ordinal features"""

df['gender']=df['gender'].map({'Female':0,'Male':1})
df['overtime']=df['overtime'].map({'Yes':1,'No':0})

education_map={'High School':1,'Bachelor':2,'Master':3,'PhD':4}
df['education_level']=df['education_level'].map(education_map)

performance_map={
    'Needs Improvement':1,
    'Statisfactory':2,
    'Good':3,
    'Excellent':4
}
df['performance_rating']=df['performance_rating'].map(performance_map)

"""One-hot encode nominal features"""

df=pd.get_dummies(
    df,
    columns=['state','city','department','job_title'],
    drop_first=True
)

"""split data"""

x=df.drop('Attrition',axis=1)
y=df['Attrition']

X_train,X_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42,stratify=y
    )

"""Feature scaling"""

scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
x_test=scalar.transform(X_test)

"""Train model"""

model=RandomForestClassifier(random_state=42)
model.fit(X_train,y_train)

"""Evaluation"""

y_pred=model.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

"""EDA"""

import matplotlib.pyplot as plt
import seaborn as sns

"""Attribution distribution"""

sns.countplot(x='Attrition',data=df)
plt.title('Attrition Distribution')
plt.show()

"""2.Gendervs attribution"""

sns.countplot(x='gender',hue='Attrition',data=df)
plt.title('Gender vs Attrition')
plt.show()
#

dept_attr=df.groupby('department_Sales')['Attrition'].mean()
dept_attr.plot(kind='bar')
plt.title("Department-wise Attribution Rate(sample)")
plt.ylabel("Attrition Rate")
plt.show()

sns.histplot(df['salary'],kde=True)
plt.title('Salary Distribution')
plt.show()

sns.boxplot(x='Attrition',y='salary',data=df)
plt.title('Salary vs Attrition')
plt.show()

sns.histplot(df['age'], bins=20,kde=True)
plt.title('Age Distribution')
plt.show()

sns.boxplot(x='Attrition',y='experience_years',data=df)
plt.title('Experience vs Attrition')
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(),cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

df['salary_difference']=df['salary']-df['base_salary']

df.groupby('Attrition')['salary_difference'].mean()

sns.barplot(x='Attrition', y='salary_difference', data=df)
plt.title('Average Salary Difference by Attrition Status')
plt.xlabel('Attrition (0 = No, 1 = Yes)')
plt.ylabel('Average Salary Difference')
plt.show()

